import React from 'react';

export default {
  principales: {
    puesto: '',
    nombre: '',
    plaza: '',
    periodo: '',
    evalTotal: '',
    vacio: -1,
    stepper: 1,
    permisoAutorizar: -1,
    usuarioIndicador: true,
    idUsuario: null,
    idPeriodo: null,
    usuarioLogeado: null,
    autorizador: '',
  },
  resumido: {
    bandPopover: false,
    cabeceras: [],
    datos: [],
    nomIndicador: '',
    detallado: [],
  },
  historial:{
    datos: [],
    cabeceras: [
      {
        name: 'Empleado',
        label: 'Empleado',
        options: {
          filter: false,
        },
      },
      {
        name: 'Puesto',
        label: 'Puesto',
        options: {
          filter: false,
        },
      },
      {
        name: 'Anio',
        label: 'Año',
        options: {
          filter: false,
        },
      },
      {
        name: 'Resultado',
        label: 'Resultado',
        options: {
          filter: false,
        },
      },
      {
        name: 'Estatus',
        label: 'Estatus periodo',
        options: {
          filter: false,
        },
      },
      {
        name: 'EstatusEvaluacion',
        label: 'Estatus indicador',
        options: {
          filter: false,
        },
      },
      {
        name: 'options',
        label: ' ',
        options: {
          filter: false,
        },
      },
    ],
  },
  cualitativos: {
    cabeceras: [
      {
        nombre: <React.Fragment>&nbsp;&nbsp;&nbsp;PESO&nbsp;&nbsp;&nbsp;</React.Fragment>,
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'Peso',
        backgroundColor: '#F5F5F5',
        color: '#424242',
        // width: '10%',
      },
      {
        nombre: 'VALORACIÓN DISCRECIONAL (Objetivos tácticos y de desempeño personal)',
        // colSpan: 8,
        width: '60%',
        textAlign: 'center',
        campo: 'Indicador',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'R. Año anterior',
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'ResultadoAnt',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'Resultado',
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'Resultado',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'Puntos',
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'Puntos',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
    ],
    datos: [],
  },
  cuantitativos: {
    encabezados: [
      {
        nombre: '',
        colSpan: 2,
        textAlign: 'center',
      },
      {
        nombre: 'RANGO',
        colSpan: 2,
        textAlign: 'center',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'CUMPLIMIENTO',
        colSpan: 3,
        textAlign: 'center',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'PUNTAJE',
        colSpan: 2,
        textAlign: 'center',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
    ],
    cabeceras: [
      {
        nombre: <React.Fragment  key='12333'>&nbsp;&nbsp;&nbsp;PESO&nbsp;&nbsp;&nbsp;</React.Fragment>,
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'Peso',
        backgroundColor: '#F5F5F5',
        color: '#424242',
        // width: '10%',
      },
      {
        nombre: 'INDICADOR',
        // colSpan: 2,
        width: '20%',
        textAlign: 'center',
        campo: 'Indicador',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'Mínimo',
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'ObjetivoMin',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'Máximo',
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'ObjetivoMax',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'Objetivo',
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'Objetivo',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: <React.Fragment key='1234'>Resultado Evaluación <br key='12333443' /> Anterior</React.Fragment>,
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'ResultadoAnt',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: <React.Fragment key='123'>Resultado Año <br key='12222333' />Evaluado</React.Fragment>,
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'Resultado',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'Puntos',
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'Puntos',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
      {
        nombre: 'Estatus',
        // colSpan: 1,
        width: '10%',
        textAlign: 'center',
        campo: 'Estatus',
        backgroundColor: '#F5F5F5',
        color: '#424242',
      },
    ],
    datos: [],
  },
  imagen: {
    estatusImagen: null,
    imagenActiva: false,
    anchorEl: null,
  },
  descargaMasivaInfo: {
    usuarios: [],
  },
}