export default {
  stepper: 0,
  cargando: false,
  departamento: '',
  tipoTicket: '',
  plazaSeleccionada:'',
  anioCorte:'',
  aCorteDe:'',
  periodoCorte:'',
  indicadorPor:'',
  arrDepartamentos: [],
  arrTipoTicket: [],
  arrPlazas: [],
  arrAnios: [],
  arrSemanas: [],
  arrMeses: [],
  mostrarGrafica: false,
  datosReportesOCKyOEProceso: [],
  datosReportesOCKyOEPuesto: [],
  datosReportesOCKyOEPuestoTotales: [],
  datosGrafProceso: [],
  datosGrafPuesto: [],
  arrGrafBarrasPuesto: [],
  arrSemanaRetailProceso: [],
  arrCumplimientoProceso: [],
  dataTablaPuesto: [],
  arrGrafPuesto: [{
    Nombre:'',
    Semana:[],
    Cumpl:[],
  }],
};