export default {
  configuracion: {
    componentes: [
      {
        tipoComponenteId: 0,
        config: { 
          isComplete:true,
          valor: '',
          valorNumero: -1,
          nomCampo: 'Título',
          tipo: 'text',
          label: '',
          value: '',
          longitud: '',
          helpertextLongitud:'',
          error: false,
          errorTipo: false,
          errorLongitud: false,
          helpertext:'',
          helpertext2:'',
          requerido: false,
          colorearBorde: false,
          relacionaOtro: false,
          requeridoRelacion: false,
          cantidadarchivos: '',
          tamañoarchivos:'',
          tipoArchivo: 'picture',
          itemsCatalogo: [],
          relaciones: {},
          opciones: [
            {
              id: '',
              value: '',
              label:'Opcion',
              error:false,
              icon:'',
            },
          ],
          

        },
      },
      {
        tipoComponenteId: 1,
        config: {
          isComplete:true,
          valor: '',
          valorNumero: -1,
          nomCampo: 'Descripción',
          tipo: 'text',
          label: '',
          value: '',
          longitud: '',
          helpertextLongitud:'',
          error: false,
          error2: false,
          errorTipo: false,
          errorLongitud: false,
          helpertext:'',
          helpertext2:'',
          requerido: false,
          colorearBorde: false,
          relacionaOtro: false,
          requeridoRelacion: false,
          cantidadarchivos: '',
          tamañoarchivos: '',
          tipoArchivo: 'picture',
          itemsCatalogo: [],
          opciones: [
            {
              id: '',
              value: '',
              label:'Opcion',
              error:false,
              icon:'',
              isChecked:'',
            },
          ],
        },
      },
    ],
    etapasCheck:false,
    autorizacion:false,
    seguimiento:false,
    camposInvalidos:false,
    divSelecionado: 0,
    campoSelecionado: 0,
    selectionServicio:'',
    errores:{
      errorServicio:false,
      errorTiempoRespuesta:false,
      errorCierreRespuesta:false,
      errorPriorizdor:false,
    },
    selectionTipo: '',
    selectionPrioriza: '',
    selectionPuesto:'',
    // selectionDepartamento: '',
    selectionDepartamento: [],
    selectionCierreRespuesta: '',
    selectionPermisosPuesto:[],
    tipoCierreRespuesta:'horas',
    selectionTiempoRespuesta: '',
    selectionTiempoSLA: '',
    tipoTiempoRespuesta:'horas',
    servicioPrioriza: [],
    servicioTipos: [],
    servicioDepartamentos: [],
    servicioPuestos: [],
    tiposCampos: [
      {
        id: 'textocorto',
        label: 'Texto corto',
        icono: 'shorttext',
      },
      {
        id: 'textolargo',
        label: 'Texto largo',
        icono: 'largetext',
      },
      {
        id: 'seleccionmulti',
        label: 'Selección múltiple',
        icono: 'checkbox',
      },
      {
        id: 'seleccionsimple',
        label: 'Selección simple',
        icono: 'simple',
      },
      {
        id: 'listadesplegable',
        label: 'Lista desplegable',
        icono: 'lista',
      },
      {
        id: 'archivo',
        label: 'Cargar archivo',
        icono: 'cloudupload',
      },
      {
        id: 'catalogo',
        label: 'Catálogo',
        icono: 'catalogo',
      },
    ],
    etapas:[],
    etapasParaBorrar:[],
    idPlantilla:"",
    arrCatalogos:[],
    redirectCamposEspeciales:false,
  },
  redirect:false,
  stepper: 0,
  configEtapas:"",
  configuracionCampos:"",
  

};