export default {
  // GLOBAL -------------------------------------------------------------------------------------///
  stepper: 0,
  numUsuarioLogeado: 0,
  nomUsuarioLogeado:'',
  idDepartamentoLogeado: 0,
  idRolUsuarioLogeado: 0,
  plazaUsuarioLogeado: 2,
  imagenAvatar: '',
  IdPortafolio:'',
  IdProyecto: '',
  IdPlantilla: '',
  // estatusProyectoSeleccionado,
  // IdUsuarioAutorizador:"",
  // imagenAvatar: '',

  // LINEA BASE -------------------------------------------------------------------------------------///

  lineaBase:{
    
    pantallaTickets:false,
    IdTicketLineaBase:'',
    estatusProyectoSeleccionado:"",
    tablaPendientes:false,
    observacion:"",
    modalobservacionesFormulario:false,
    Responsable:'',
    AbrirObservaciones:false,
    IdAutorizador:"",
    IdLineaBase: '',
    LineaBaseActiva: '',
    modalAutorizacion:0,
    idProyecto:"",
    idAutorizacion:"",
    arrColumnaComponente: [],
    arrCabeceraComponente:[],
    arrCabeceras:[],
    arrCabecerasExtras:[],
    arregloComponentes:[],
    arregloComponentesExtras:[],
    arrCabeceraEtapas:[],
    arrLineasBase: [],
    arrEtapas: [],
    cabeceras:[],
    arrPlazas:[],
    arrDepartamentos:[],
    arrPuestos:[],
    arrRecursos:[],
    arrRecursosInvitarAmigo:[],
    fechaValida: true,
    fecInicio: null,
    fecFin:null,
    fecInput: null,
    selectRecurso: '',
    openModal: false,
    rowSelected:'',
    cellSelected:'',
    autoAsignarmelo: false,
    recursoSeleccionado: 0,
    openModalNColumna: false,
    openConfirmacionBorrar: false,
    plazaSeleccionadaRecurso: 0,
    departamentoSeleccionadoRecurso: 0,
    puestoSeleccionadoRecurso: 0,
    recursoSeleccionadoRecurso: 0,
    nomrecursoSeleccionadoRecurso:'',
    disabledDepartamento: true,
    arrDepartamentosInvitar:[],
    tamanioTabla: 95,
    nombreNColumna:'',
    tipoDatoNColumna: '',
    openMenuTabla: false,
    openModalEditarColumna: false,
    anchorElSeleccionado: null,
    cabeceraSeleccionada: '',
    openModalObservaciones: false,
    departamentoInvitarAmigo:'',
    openModalInvitarAmigo: false,
    openModalSalir:false,
    openModalGenerarLB:false,
    openModalCancelarCopia:false,
    valorInvitarAmigo:'',
    Copia: '',
    Editando: false,
    Invitado: '',
    // --
    bandejaTickets: {
      idTicketSelected: 0,
      plazasAutorizadas:[],
      tabSelectedDetails:0,
      tabEtapas: false,
      idTicket:3263,
      tabSelected: 0,
      ticketsDetails: {
        departamentos: [],
        departamento: {
          'id': '',
          'nombre': '',
        },
        openModal: false,
        tipoJustificacion: '',
        disabledChat: false,
        valueTextModal:'',
        mensajeValue:'',
        urlFile: '',
        dataBlop: '',
        chatMounted: false,
        mensajes:[],
        plantillas: [],
        plantillaSelected: {
          'id' : '',
        },
        plantilla: {
          tipoForma: [],
        },
      },
      ticketSelected:[],
    },
  },
  

  // PORTAFOLIOS -------------------------------------------------------------------------------------///

  portafolios: {
    idPortafolio:"",
    modalFormulario:false,
    colorPortafolio:{hex:"rgb(248, 231, 28)"},
    mostrarColorPortafolio:false,
    nombrePortafolio:"",
    errores:{
      errorNombrePortafolio:false,
    },
    carpetas:[],
    abrirOpcionesPortafolio:false,
    abrirEdicion:false,
    idxPortafolio:"",
    abrirPop:false,
  },

  // LISTADOS PROYECTOS -------------------------------------------------------------------------------------///

  listadoProyectos: {
    modalGuardadoProyecto:false,
    condiciones:[
      {id:1,condicion:">"},
      {id:2,condicion:">="},
      {id:3,condicion:"="},
    ],
    ticketsEnCancelacion:[],
    impactoEnEdicion:'',
    idImpactoSeleccionado:"",
    openModalBorradoImpactos:false,
    openModalCanceladoProyecto:false,
    impactosVacios:false,
    openModalCerrarProyecto:false,
    realAcceso:false,
    idImpactoDocumento:"",
    idImpactoRiesgo:"",
    impactosDocumentos:[],
    formImpactosDocumentos:false,
    observaciones:[],
    nuevoImpactoDocumento:false,
    modalImpactos:false,
    modalRiesgos:false,
    nombreDocumentos:"",
    objetivoDocumentos:"",
    realDocumentos:"",
    unidadDocumentos:"",
    cumplimientoDocumentos:"",
    ponderacionDocumentos:"",
    condicionDocumentos:"",
    cabeceras: [
      {
        name: 'Estatus',
        label: 'Estatus',
      },
      {
        name: 'Progreso',
        label: 'Progreso',
      },
      {
        name: 'Fechas',
        label: 'Fechas',
      },
      {
        name: 'fechaCreacion',
        label: 'Fecha',
      },
      {
        name: 'Prioridad',
        label: 'Prioridad',
      },
      {
        name: 'Responsable',
        label: 'Responsable',
      },
      {
        name: '',
        label: ' ', 
        options: {
        },
      },
    ],
    modalProyectos : false,
    plantillas:[],
    plantillaSeleccionada:[],
    prioridades: [
      {
        id: 1,
        nombre: 'Baja',
      },
      {
        id: 2,
        nombre: 'Mediana',
      },
      {
        id: 3,
        nombre: 'Alta',
      },
    ],
    prioridadSeleccionada:"",
    empleadoSeleccionado:[],
    nombreProyecto:"",
    colorProyecto:{hex:"rgb(248, 231, 28)"},
    empleados:[],
    idProyecto:"",
    idPortafolio:{
      item:{
        IdPortafolio:"",
      },
    },
    nombrePortafolioSeleccionado:"",
    colorPortafolioSeleccionado:"",
    proyectos:[],
    enEdicion:"",
    errores:{
      errorTipoProyecto:true,
      errorNombreProyecto:false,
      errorPrioridad:false,
      errorResponsable:true,
      errorRepetido:false,
    },
    fechas:{
      fechaInicio:null,
      fechaFin:null,
      fechaInput:null,

      fechaInicioRes:null,
      fechaFinRes:null,
      fechaInputRes:null,
    },
    estatusSeleccionado:"",
    responsableSeleccionado:[],
    responsableEstatus:true,
    cerrarFiltro:false,
    tabSelectedDetails:0,
    openModalObservaciones:false,
    cabecerasImpactoDocumentos: [
      {
        name: 'Nombre',
        label: 'Nombre',
      },
      {
        name: 'Condicion',
        label: 'Condición',
      },
      {
        name: 'Objetivo',
        label: 'Objetivo',
      },
      {
        name: 'Real',
        label: 'Real',
      },
      {
        name: 'Unidad',
        label: 'Unidad',
      },
      {
        name: 'Cumplimiento',
        label: 'Cumplimiento',
      },
      {
        name: 'Ponderacion',
        label: 'Ponderación',
      },
      {
        name: 'Calificacion',
        label: 'Calificación',
      },
      {
        name: 'options',
        label: 'Opciones', 
        options: {
        },
      },
    ],
    
  },
  //  -------------------------------------------------------------------------------------///
  
};
