import styled from "styled-components";

export const Container = styled.div`
  display: flex;
  flex-direction: ${props => {
    const { flexDirection = "row" } = props;
    const directions = ["row", "column"];
    const dir = directions.includes(flexDirection) ? flexDirection : "row";

    return `${dir}`;
  }};
  width: ${props => {
    const { width = 100 } = props;
    return `${width}%`;
  }};
`;

export const ColumnContainer = styled.div``;

// TICKET GRANDE
// tipoForma:[
//   {
//     "tipoComponenteId": 6,
//     "config": {
//       "valorNumero": 2,
//       "nomCampo": "Plaza",
//       "isComplete": true,
//       "valor": [],
//       "tamañoarchivos": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "requerido": true,
//       "helpertextLongitud": "",
//       "value": 1,
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": true,
//       "itemsCatalogo": [
//         {
//           "Id": 1,
//           "IdPlazaReal": 2,
//           "Descripcion": "culiacan",
//         },
//         {
//           "Id": 2,
//           "IdPlazaReal": 6,
//           "Descripcion": "mazatlan",
//         },
//         {
//           "Id": 4,
//           "IdPlazaReal": 3,
//           "Descripcion": "ensenada",
//         },
//         {
//           "Id": 5,
//           "IdPlazaReal": 4,
//           "Descripcion": "la paz",
//         },
//         {
//           "Id": 7,
//           "IdPlazaReal": 9,
//           "Descripcion": "corporativo",
//         },
//         {
//           "Id": 8,
//           "IdPlazaReal": 1,
//           "Descripcion": "cabo san lucas",
//         },
//         {
//           "Id": 8,
//           "IdPlazaReal": 5,
//           "Descripcion": "los cabos",
//         },
//       ],
//       "helpertext2": "",
//       "tipoArchivo": "picture",
//       "relaciones": [
//         {
//           "IdCatalogo": 2,
//           "Nombre": "Plazas",
//           "SP": "proc_Catalogo_obtenerDatosPlazas",
//           "Parametros": "{\"BaseDatos\":\"\",\"LinkServer\":\"\"}",
//           "Para": 3,
//           "ParaNombre": "Desarrollos",
//           "Desde": null,
//           "DesdeNombre": null,
//         },
//       ],
//       "helpertext": "",
//       "errorTipo": false,
//       "requeridoRelacion": false,
//       "errorLongitud": false,
//     },
//   },
//   {
//     "tipoComponenteId": 6,
//     "config": {
//       "valorNumero": 3,
//       "nomCampo": "Desarrollo",
//       "isComplete": true,
//       "valor": [],
//       "tamañoarchivos": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "error2": false,
//       "requerido": true,
//       "helpertextLongitud": "",
//       "value": 45,
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//           "isChecked": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": true,
//       "itemsCatalogo": [
//         {
//           "Id": 1,
//           "Descripcion": "valle alto",
//         },
//         {
//           "Id": 51,
//           "Descripcion": "otros",
//         },
//         {
//           "Id": 45,
//           "Descripcion": "privada valle alto",
//         },
//       ],
//       "helpertext2": "",
//       "tipoArchivo": "picture",
//       "relaciones": [
//         {
//           "IdCatalogo": 3,
//           "Nombre": "Desarrollos",
//           "SP": "proc_Catalogo_obtenerDatosDesarrollos",
//           "Parametros": "{\"BaseDatos\":\"\",\"LinkServer\":\"\",\"Plazas\":\"\"}",
//           "Para": 4,
//           "ParaNombre": "Etapas",
//           "Desde": 2,
//           "DesdeNombre": "Plazas",
//         },
//       ],
//       "helpertext": "",
//       "errorTipo": false,
//       "requeridoRelacion": true,
//       "errorLongitud": false,
//     },
//   },
//   {
//     "tipoComponenteId": 6,
//     "config": {
//       "valorNumero": 4,
//       "nomCampo": "Etapa",
//       "isComplete": true,
//       "valor": [],
//       "tamañoarchivos": "",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": 2,
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": true,
//       "itemsCatalogo": [
//         {
//           "Id": 2,
//           "Descripcion": "valle alto privada 7",
//         },
//         {
//           "Id": 15,
//           "Descripcion": "privada 5 va",
//         },
//         {
//           "Id": 16,
//           "Descripcion": "privada 6 valle alto",
//         },
//       ],
//       "helpertext2": "",
//       "relaciones": [
//         {
//           "IdCatalogo": 4,
//           "Nombre": "Etapas",
//           "SP": "proc_Catalogo_obtenerDatosEtapas",
//           "Parametros": "{\"BaseDatos\":\"\",\"LinkServer\":\"\",\"Plazas\":\"\",\"Desarrollos\":\"\"}",
//           "Para": 8,
//           "ParaNombre": "Prototipos",
//           "Desde": 3,
//           "DesdeNombre": "Desarrollos",
//         },
//       ],
//       "helpertext": "",
//       "requeridoRelacion": true,
//     },
//   },
//   {
//     "tipoComponenteId": 6,
//     "config": {
//       "valorNumero": 8,
//       "nomCampo": "Prototipo",
//       "isComplete": true,
//       "valor": [],
//       "tamañoarchivos": "",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": 317,
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": false,
//       "itemsCatalogo": [
//         {
//           "Id": 317,
//           "Descripcion": "platino plus priv 7",
//         },
//         {
//           "Id": 318,
//           "Descripcion": "platino priv 7",
//         },
//         {
//           "Id": 331,
//           "Descripcion": "lote ",
//         },
//         {
//           "Id": 361,
//           "Descripcion": "platino plus muestra",
//         },
//       ],
//       "helpertext2": "",
//       "relaciones": [
//         {
//           "IdCatalogo": 8,
//           "Nombre": "Prototipos",
//           "SP": "proc_Catalogo_obtenerDatosPrototipos",
//           "Parametros": "{\"BaseDatos\":\"\",\"LinkServer\":\"\",\"Plazas\":\"\",\"Desarrollos\":\"\",\"Etapas\":\"\"}",
//           "Para": null,
//           "ParaNombre": null,
//           "Desde": 4,
//           "DesdeNombre": "Etapas",
//         },
//       ],
//       "helpertext": "",
//       "requeridoRelacion": true,
//     },
//   },
//   {
//     "tipoComponenteId": 6,
//     "config": {
//       "valorNumero": 1,
//       "nomCampo": "Compañía",
//       "isComplete": true,
//       "valor": [],
//       "tamañoarchivos": "",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": 8,
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": true,
//       "itemsCatalogo": [
//         {
//           "Id": 5,
//           "Descripcion": "05 - promotora sinaloense de vivienda",
//         },
//         {
//           "Id": 8,
//           "Descripcion": "08 - constructura fincasin",
//         },
//         {
//           "Id": 13,
//           "Descripcion": "13 - promourban",
//         },
//         {
//           "Id": 15,
//           "Descripcion": "15 - patrimonio y capital",
//         },
//       ],
//       "helpertext2": "",
//       "relaciones": [
//         {
//           "IdCatalogo": 1,
//           "Nombre": "Empresas",
//           "SP": "proc_Catalogo_obtenerDatosEmpresas",
//           "Parametros": "{\"BaseDatos\":\"\",\"LinkServer\":\"\"}",
//           "Para": 5,
//           "ParaNombre": "Centros_De_Costos",
//           "Desde": null,
//           "DesdeNombre": null,
//         },
//       ],
//       "helpertext": "",
//       "requeridoRelacion": false,
//     },
//   },
//   {
//     "tipoComponenteId": 6,
//     "config": {
//       "valorNumero": 5,
//       "nomCampo": "Centro de Costo",
//       "isComplete": true,
//       "valor": [],
//       "tamañoarchivos": "",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": "4GG",
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": true,
//       "itemsCatalogo": [
//         {
//           "Id": "4GG",
//           "Descripcion": "4GG - obra en proc  edif privada 7 valle alto",
//         },
//       ],
//       "helpertext2": "",
//       "relaciones": [
//         {
//           "IdCatalogo": 5,
//           "Nombre": "Centros_De_Costos",
//           "SP": "proc_Catalogo_obtenerDatosCC",
//           "Parametros": "{\"BaseDatos\":\"\",\"LinkServer\":\"\",\"Empresas\":\"\"}",
//           "Para": 6,
//           "ParaNombre": "Obras",
//           "Desde": 1,
//           "DesdeNombre": "Empresas",
//         },
//       ],
//       "helpertext": "",
//       "requeridoRelacion": true,
//     },
//   },
//   {
//     "tipoComponenteId": 6,
//     "config": {
//       "valorNumero": 6,
//       "nomCampo": "Obra",
//       "isComplete": true,
//       "valor": [],
//       "tamañoarchivos": "",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": "A1G",
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": false,
//       "itemsCatalogo": [
//         {
//           "Id": "DD3",
//           "Descripcion": "DD3 - obra extra 2018 fincasin privada 7",
//         },
//         {
//           "Id": "DE5",
//           "Descripcion": "DE5 - obra extra 2018 contratista privada 7",
//         },
//         {
//           "Id": "393",
//           "Descripcion": "393 - oe 2015 fincasin valle alto privada 7",
//         },
//         {
//           "Id": "399",
//           "Descripcion": "399 - oe 2015 contratista valle alto privada 7",
//         },
//         {
//           "Id": "A1G",
//           "Descripcion": "A1G - obra extra 2016 fincasin valle alto privada 7",
//         },
//         {
//           "Id": "A1N",
//           "Descripcion": "A1N - obra extra 2016 contratistas valle alto privada 7",
//         },
//         {
//           "Id": "A1P",
//           "Descripcion": "A1P - oe urbanizacion 2016 fincasin privada 7",
//         },
//         {
//           "Id": "CBE",
//           "Descripcion": "CBE - vtp vii 02 plataformas sub eti ftei on 11oct2014",
//         },
//         {
//           "Id": "CCS",
//           "Descripcion": "CCS - inicio may15 platino pl m118 lt 1-5 y m120 lt 1-3",
//         },
//         {
//           "Id": "CCT",
//           "Descripcion": "CCT - inicios mayo 2015 platino mz 118 lt 06 - 14 line 1",
//         },
//         {
//           "Id": "CDB",
//           "Descripcion": "CDB - vtp vii 00 platafo sub cierre cbe etifteion 140515",
//         },
//         {
//           "Id": "CDE",
//           "Descripcion": "CDE - vtp vii 00 muros de cont mlbp djo eti fteii on 21m",
//         },
//         {
//           "Id": "CDM",
//           "Descripcion": "CDM - inicio jun2015 platino plus mz 120 lt 04-07 line 2",
//         },
//         {
//           "Id": "CDP",
//           "Descripcion": "CDP - inicios jun 2015 platino mnz 118 lt 15-21 linea 2 ",
//         },
//         {
//           "Id": "CDQ",
//           "Descripcion": "CDQ - inicio jul2015 platino plus mz 120 lt 08-012 lin 2",
//         },
//         {
//           "Id": "CDR",
//           "Descripcion": "CDR - inicio jul2015 platino plus mz 119 l 01-12 lin 3-4",
//         },
//         {
//           "Id": "CDU",
//           "Descripcion": "CDU - inicio jun2015 platino plus m 120-121 l 15-25 y 21",
//         },
//         {
//           "Id": "CDY",
//           "Descripcion": "CDY - vtp vii 00 muros de cont sobrestante djo eti ftei ",
//         },
//         {
//           "Id": "CED",
//           "Descripcion": "CED - vtp vii 00 muros de cont bailarina djo eti ftei on",
//         },
//         {
//           "Id": "CEL",
//           "Descripcion": "CEL - inicio ago-oct 15 mz 120 y 121 platino plus priv 7",
//         },
//         {
//           "Id": "CEN",
//           "Descripcion": "CEN - vtp vii 00 barda perim perdura stone sub eti ftei ",
//         },
//         {
//           "Id": "CEQ",
//           "Descripcion": "CEQ - vtp vii 01 barda patio puertas sub eti ftei on 07s",
//         },
//         {
//           "Id": "CES",
//           "Descripcion": "CES - bardas perimetrales - mando intermedio privada 7",
//         },
//         {
//           "Id": "CEW",
//           "Descripcion": "CEW - vtp vii 00 barda perim mdo inter djo eti ftei on 0",
//         },
//         {
//           "Id": "CFE",
//           "Descripcion": "CFE - renivelacion de cocheras en viviendas privada 7",
//         },
//         {
//           "Id": "CFM",
//           "Descripcion": "CFM - vtp vii 00 muros cont aplanad djo etifteioc 221215",
//         },
//         {
//           "Id": "CFR",
//           "Descripcion": "CFR - muros de contencion-mando intermedio privada 7",
//         },
//         {
//           "Id": "CFT",
//           "Descripcion": "CFT - oe detallado de bardas en privada 7",
//         },
//         {
//           "Id": "CFV",
//           "Descripcion": "CFV - inic mar16 platino mnz 121 lte 9-11 y 14-18 priv 7",
//         },
//         {
//           "Id": "CFX",
//           "Descripcion": "CFX - inicios abr16 platino mnz 121 lte 01 - 08 priv 7",
//         },
//         {
//           "Id": "CFY",
//           "Descripcion": "CFY - inic abr16 platino plus mnz 121 lte 12 y 13 priv 7",
//         },
//         {
//           "Id": "CG6",
//           "Descripcion": "CG6 - rejilla p/paso pluvial en barda perimetral priv. 7",
//         },
//         {
//           "Id": "CGE",
//           "Descripcion": "CGE - vtp vii 00 muros cont compl djo eti ftei on 150216",
//         },
//         {
//           "Id": "CK5",
//           "Descripcion": "CK5 - obra extra fincasin",
//         },
//         {
//           "Id": "CP9",
//           "Descripcion": "CP9 - obra extra 2017 fincasin valle alto priv 7",
//         },
//         {
//           "Id": "CQ8",
//           "Descripcion": "CQ8 - o.e. 2017 contratistas valle alto priv 7",
//         },
//         {
//           "Id": "CW1",
//           "Descripcion": "CW1 - vtp vii 00 muros de contencion pintura djo etvii",
//         },
//         {
//           "Id": "P0A",
//           "Descripcion": "P0A - obra inicial privada 7",
//         },
//         {
//           "Id": "CV3",
//           "Descripcion": "CV3 - obra extra barda privada 7 2017",
//         },
//         {
//           "Id": "DQ6",
//           "Descripcion": "DQ6 - oe sum e inst. de ventanas, domos y volados priv 7",
//         },
//       ],
//       "helpertext2": "",
//       "relaciones": [
//         {
//           "IdCatalogo": 6,
//           "Nombre": "Obras",
//           "SP": "proc_Catalogo_obtenerDatosObras",
//           "Parametros": "{\"BaseDatos\":\"\",\"LinkServer\":\"\",\"Empresas\":\"\",\"Centros_De_Costos\":\"\"}",
//           "Para": 7,
//           "ParaNombre": "Tipos de Obra",
//           "Desde": 5,
//           "DesdeNombre": "Centros_De_Costos",
//         },
//       ],
//       "helpertext": "",
//       "requeridoRelacion": true,
//     },
//   },
//   {
//     "tipoComponenteId": 4,
//     "config": {
//       "valorNumero": -1,
//       "nomCampo": "Tipo de Obra",
//       "isComplete": true,
//       "valor": "Edificación",
//       "tamañoarchivos": "",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": "",
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "Urbanización",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//         {
//           "id": "",
//           "value": "Edificación",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//         {
//           "id": "",
//           "value": "Infraestructura",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//         {
//           "id": "",
//           "value": "Equipamiento",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": false,
//       "itemsCatalogo": [],
//       "helpertext2": "",
//       "relaciones": {},
//       "helpertext": "",
//       "requeridoRelacion": false,
//     },
//   },
//   {
//     "tipoComponenteId": 1,
//     "config": {
//       "valorNumero": -1,
//       "nomCampo": "Descripción de la solicitud",
//       "isComplete": true,
//       "valor": "obra",
//       "tamañoarchivos": "",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": "texto",
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "600",
//       "relacionaOtro": false,
//       "itemsCatalogo": [],
//       "helpertext2": "",
//       "relaciones": {},
//       "helpertext": "",
//       "requeridoRelacion": false,
//     },
//   },
//   {
//     "tipoComponenteId": 1,
//     "config": {
//       "valorNumero": -1,
//       "nomCampo": "Motivo de la solicitud",
//       "isComplete": true,
//       "valor": "venta de casas",
//       "tamañoarchivos": "",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": "texto",
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "id": "",
//           "value": "",
//           "label": "Opcion",
//           "error": false,
//           "icon": "",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "600",
//       "relacionaOtro": false,
//       "itemsCatalogo": [],
//       "helpertext2": "",
//       "relaciones": {},
//       "helpertext": "",
//       "requeridoRelacion": false,
//     },
//   },
//   {
//     "tipoComponenteId": 5,
//     "config": {
//       "valorNumero": -1,
//       "nomCampo": "Bitácora",
//       "isComplete": true,
//       "valor": [
//         {},
//       ],
//       "tamañoarchivos": "10",
//       "tipoCierreRespuesta": "",
//       "error": false,
//       "cantidadarchivos": "2",
//       "tipoTiempoRespuesta": "",
//       "requerido": true,
//       "value": "",
//       "colorearBorde": false,
//       "opciones": [
//         {
//           "value": "427e087c8bde9fd48c46ec62edd11374.jpg",
//           "url": "http://172.17.10.79:1337/uploads/084fef57cf2747f5954bf4b342600b49.jpg",
//         },
//       ],
//       "label": "",
//       "tipo": "text",
//       "longitud": "",
//       "relacionaOtro": false,
//       "itemsCatalogo": [],
//       "helpertext2": "",
//       "files": {},
//       "tipoArchivo": "pdf",
//       "relaciones": {},
//       "helpertext": "",
//       "requeridoRelacion": false,
//     },
//   },
// ],