export default {
  permisos: {
    normales: {
      sololectura:1,
      registrar:1,
      editar:1,
      eliminar:1,
    },
    especiales: {
  
    },
  },
  modulosTabla: {
    order: 'asc',
    orderBy: '',
    selected: [],
    data: [],
    filterData: [],
    page: 0,
    rowsPerPage: 5,
    open: false,
    openSearch: false,
    searchText: '',
    openModal: false,
    openMenuContextual: false,
    stepper: 0,
    activarRegistros: null,
  },
  nuevoModulo:{
    textFieldModulo:'',
    textFieldDescripcion:'',
    stepperaddmodulo:1,
    openM:false,
    textFieldNombreFuncion:'',
    nombreBottonModalAddFuncion:0,
    getEmpresas:[],
    selectEmpresa:[],
    getModulos:[],
    selectModulos:[],
    idtipoagrupador:[],
    urlFuncion:[],
    urlFuncionSlc:-1,
    URLFuncionId:[],
    mensajeLabel:'',
    vacioNombreModulo:false,
    openModalAddModulo:false,
    IdRol:0,
    IdEmpresa:0,
    IdRolEmpresa: 0,
    FuncionId:0,
    usuario: 0,
    errorTipoAgrupador:false,
    errorNombreFuncion:false,
    labelTipoAgrupador:'Requerido*',
    labelNombreFuncion:'Requerido*',
    labelUrlFuncion:'Requerido*',
    openMensajeSalirFuncion:false,
    visualizaTabla:false,
    nombreTipoAgrupador:'',
    datosGuardar:{},
    actualizaPermisos:false,
    modalFuncionesDisable:false,
    moduloSoloLecturaRol:false,
    moduloSoloLecturaEmpresa:false,
    nombreModuloSinActualizar:'',
    lista:[],
    opciones:[],
    loading: false,
  },
}