export default {
  permisos: {
    normales: {
      sololectura:1,
      registrar:1,
      editar:1,
      eliminar:1,
    },
    especiales: {
  
    },
  },
  modulosTabla: {
    order: 'asc',
    orderBy: '',
    selected: [],
    data: [],
    filterData: [],
    page: 0,
    rowsPerPage: 5,
    open: false,
    openSearch: false,
    searchText: '',
    openModal: false,
    openMenuContextual: false,
    stepper: 0,
    activarRegistros: null,
  },
  nuevoModulo:{
    textFieldModulo:'',
    textFieldDescripcion:'',
    stepperaddmodulo:0,
    openM:false,
    textFieldNombreFuncion:'',
    nombreBottonModalAddFuncion:0,
    tipoAgrupador:[],
    tipoAgrupadorSlc:-1,
    idtipoagrupador:[],
    urlFuncion:[],
    urlFuncionSlc:-1,
    URLFuncionId:[],
    mensajeLabel:'',
    vacioNombreModulo:false,
    openModalAddModulo:false,
    IdModulo:0,
    FuncionId:0,
    usuario:2,
    errorTipoAgrupador:false,
    errorNombreFuncion:false,
    labelTipoAgrupador:'Requerido*',
    labelNombreFuncion:'Requerido*',
    labelUrlFuncion:'Requerido*',
    openMensajeSalirFuncion:false,
    visualizaTabla:false,
    nombreTipoAgrupador:'',
    datosGuardar:[],
    datosGuardarEliminados:[],
    actualizaFuncion:false,
    modalFuncionesDisable:false,
    moduloSoloLectura:false,
    nombreModuloSinActualizar:'',
  },
}
