export default {
  configuracion: {
    componentes: [
      {
        tipoComponenteId: 0,
        config: {
          nombreEtapa:"",
          plazaId : "",
          isComplete:true,
          valor: '',
          valorNumero:-1,
          nomCampo: 'Título',
          tipo: 'text',
          label: '',
          value: '',
          longitud: '',
          helpertextLongitud:'',
          error: false,
          errorTipo: false,
          errorLongitud: false,
          helpertext:'',
          helpertext2:'',
          requerido: false,
          colorearBorde: false,
          requeridoRelacion: false,
          relacionaOtro:false,
          cantidadarchivos: '',
          tamañoarchivos:'',
          tipoArchivo: 'picture',
          itemsCatalogo: [],
          relaciones: {},
          opciones: [
            {
              id: '',
              value: '',
              label:'Opcion',
              error:false,
              icon:'',
            },
          ],
          

        },
      },
      {
        tipoComponenteId: 1,
        config: {
          nombreEtapa:"",
          plazaId : "",
          isComplete:true,
          valor: '',
          valorNumero: -1,
          nomCampo: 'Descripción',
          tipo: 'text',
          label: '',
          value: '',
          longitud: '',
          helpertextLongitud:'',
          error: false,
          error2: false,
          errorTipo: false,
          errorLongitud: false,
          helpertext:'',
          helpertext2:'',
          requerido: false,
          colorearBorde: false,
          requeridoRelacion: false,
          relacionaOtro: false,
          cantidadarchivos: '',
          tamañoarchivos: '',
          tipoArchivo: 'picture',
          itemsCatalogo: [],
          opciones: [
            {
              id: '',
              value: '',
              label:'Opcion',
              error:false,
              icon:'',
              isChecked:'',
            },
          ],
        },
      },
    ],
    configuracionComponentesTemporales:[],
    arrCombosSeleccionados: [],
    camposInvalidos:false,
    divSelecionado: 0,
    campoSelecionado: 0,
   
    selectionServicio:'',
    errores:{
      errorServicio:false,
      errorTiempoRespuesta:false,
      errorTiempoSLA:false,
    },
    selectionTipo: '',
    selectionPrioriza: '',
    selectionDepartamento: '',
    selectionCierreRespuesta: '',
    tipoCierreRespuesta:'horas',
    selectionTiempoRespuesta: '',
    tipoTiempoRespuesta:'horas',
    servicioPrioriza: [],
    servicioTipos: [],
    servicioDepartamentos: [],
    tiposCampos: [
      {
        id: 'textocorto',
        label: 'Texto corto',
        icono: 'shorttext',
      },
      {
        id: 'textolargo',
        label: 'Texto largo',
        icono: 'largetext',
      },
      {
        id: 'seleccionmulti',
        label: 'Selección múltiple',
        icono: 'checkbox',
      },
      {
        id: 'seleccionsimple',
        label: 'Selección simple',
        icono: 'simple',
      },
      {
        id: 'listadesplegable',
        label: 'Lista desplegable',
        icono: 'lista',
      },
      {
        id: 'archivo',
        label: 'Cargar archivo',
        icono: 'cloudupload',
      },
      {
        id: 'catalogo',
        label: 'Catálogo',
        icono: 'catalogo',
      },
    ],
    arrCatalogos:[],
    soloConfigEspeciales:false,
    salirConfiguracion:false,
    datosEtapas:{},
    componentesEspeciales:[],
    IdEtapa:"",
    tiempos:[],
    componentesIniciales:[],
  },
  etapas: {
    reglas:[
      {
        nombre:'Se muestra etapa si la regla se cumple',
        config:[
          {
            valores:'',
            errorValores:false,
            campo:'',
            errorCampo:false,
            condicion:'',
            errorCondicion:false,
            valor:'',
            errorValor:false,
            campoEspecial:false,
            componentes:[
              {config:{nomCampo:"titulo"}},
            ],
            nombreEtapa:"",
          },
        ],
       
      },
    ],
    reglasTemporales:[],
    reglaSeleccionadaTemporal:999999999,
    reglaSeleccionada: 99999999,
  },
  tabla: {
    datosPlaza : [],
    cabecerasPlaza : [],
    datosEtapa : [],
    datosEtapasBorradas : [],
    cabecerasEtapa : [],  
    etapa : 1,
    plaza : '',
    idPlaza: 0,
    etapasTemporales: [],
    idPlazaTemporal:0,
    idPlantilla:0,
    modalClonar:false,
    plazaClonSeleccionada:"",
    etapasClonadas:[],
    modalBorrado:false,
    idEtapaBorrar : '',
  },
  confEtapas: {
    numeroPuestos:"",
    etapaSeleccionada:"",
    plazaId:{
      'id':'',
      'nombre':"",
    },
    plazas:[],
    plazasDestino:[],
    plazaDestinoSeleccionada: {
      'id': '',
      'nombre': '',
    },
    plazaSelected: {
      'id': '',
      'nombre': '',
    },
    rolUsuarioSelected: {
      'id': '',
      'nombre': '',
    },
    requiereSeguimiento:false,
    nombreEtapa:"",
    dependencias:[],
    tipoBusquedaUsuarios:[],
    radioRol:"",
    activarRadioRol:false,
    permitirCancelacion:false,
    puesto:"",
    dependenciaSeleccionada:{
      'id': '',
      'nombre': '',
    },
    horaInicio1:"",
    horaInicio2:"",
    horaFin1:"",
    horaFin2:"",
    tiempoSla1:0,
    tiempoSla2:0,
    configuracion:[],
    actualizarEtapa:false,
    etapaEnEdicion:[],
    reglas:[],
    guadada: false,
    errores:{
      errorPlaza:false,
      errorPlazaBusqueda:false,
      errorPuestoUsuario:false,
      errorNombreEtapa:false,
      errorHoraInicio:false,
      errorHoraFin:false,
      errorTiempoSLA:false,
      errorDependencia:false,
    },
  },
  configuracionComponentes:{},
  nuevoValor:"",
  componentesFiltrados:[],
  stepper: 2,
  redirect: false,
  validacionesConfEtapas:"",
  etapaSeleccionada:"",
  // soloConfigEspeciales:false,
};